services:
  backend-deploy:
    build:
      context: .
      target: final
    container_name: trackr-api-deploy
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq-deploy:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQ__HostName=rabbitmq-deploy

  rabbitmq-deploy:
    image: rabbitmq:3-management
    container_name: trackr-rabbitmq-deploy
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data-deploy:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data-deploy:
